### ISSUE TITLE
Build failed with an exception  please set compileSdkVersion to 30 or above 

### ISSUE THREAD

**Issue by techUdayMungalpara** [HarvestProfit/react-native-rectangle-scanner#113]
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong:
Could not determine the dependencies of task ':openCVLibrary310:bundleLibCompileToJarDebug'.
> Could not create task ':openCVLibrary310:compileDebugJavaWithJavac'. > In order to compile Java 9+ source, please set compileSdkVersion to 30 or above * Try:

**Comment by humphreyja** [comment]
Fixed in #115 

I now pull openCV4 from maven
