### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNRectangleScanner" was not found in the UIManager.

### ISSUE THREAD

**Issue by PremangiM** [HarvestProfit/react-native-rectangle-scanner#114]
Working proper in Android. Getting error for the iOS.

"react-native": "0.71.10",
"react": "18.2.0",
"react-native-rectangle-scanner": "^1.0.10",

**Comment by ismail-medhat** [comment]
this issue appear with me after upgrade RN version from 0.66.1 to 0.73.2

**Comment by tylerforsythe** [comment]
Any luck fixing this?

**Comment by humphreyja** [comment]
This is fixed in #115 I'll be releasing an update to NPM in a bit, just finishing up our mobile app that uses it so I can test it on a few devices before pushing out that update.

Thanks for pointing it out!
