### ISSUE TITLE
Possibility to switch between manual capture and auto detection ?

### ISSUE THREAD

**Issue by maknom66** [HarvestProfit/react-native-rectangle-scanner#16]
Hello,
I just wanted to know if it's possible to turn off auto detection and use it like a simple camera and turn back on the auto detection whenever needed ?

**Comment by humphreyja** [comment]
Yes. So if you don't render the [RectangleOverlay](https://github.com/HarvestProfit/react-native-rectangle-scanner/blob/master/src/RectangleOverlay.js) component, it won't draw any rectangle detection lines over the preview and wont auto capture. So you'll be left with a blank/simple camera preview. On capture, you will want to use the `initialImage` from the `onPictureProcessed({croppedImage, initialImage})` callback params which gets you the uncropped image.

Hope that helps
