### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by antoinerousseau** [HarvestProfit/react-native-rectangle-scanner#23]
That would be great to include typings, so that we wouldn't need to open the documentation to know about methods and params.

**Comment by humphreyja** [comment]
This makes sense to add and is simple enough. I'll be sure to get this included in the next release.

**Comment by humphreyja** [comment]
@antoinerousseau I haven't worked with typescript much. Would you mind checking out PR #26 to see if those typings I added work?
