### ISSUE TITLE
freeze on iPhone 8

### ISSUE THREAD

**Issue by antoinerousseau** [HarvestProfit/react-native-rectangle-scanner#24]
This module is working fine on iPhone 6 but the live photo view freezes on iPhone 8+ (although it works if I blindly capture). Any clue?

**Comment by humphreyja** [comment]
hmm ok you might need to provide a bit more details on this. 

If I understand correctly, the camera preview freezes? Is it always frozen or only after you try to capture an image? Does this lead to a crash? And a blind capture would mean capturing while the preview is frozen?

Helpful note: I have and test this package on an iPhone 8 (not the plus model). Is it the plus model? The dual cameras may be affecting this.

**Comment by antoinerousseau** [comment]
Thank you for your answer. I know it's hard to understand what's going on since there is no hard crash (no stacktrace).
The camera preview starts correcly, and after about one second, it freezes, without having to try to capture. No crash. And yes a blind capture means If I capture when it's frozen, it captures a live photo (and not the one shown on the screen that is frozen). So it's just a visual issue (but a major one).

Here is the rendered JSX:

```jsx
<SafeAreaView style={styles.container}>
  <RectangleScanner
    ref={scanner}
    style={styles.scanner}
    onPictureProcessed={handlePicture}
    onRectangleDetected={handleRectangle}
  />
  <RectangleOverlay
    detectedRectangle={rect}
    allowDetection
    onDetectedCapture={handleCapture}
    backgroundColor="rgba(255,165,0,0.2)"
    borderColor="rgb(255,165,0)"
    borderWidth={4}
    detectedBackgroundColor="rgba(0,175,25,0.2)"
    detectedBorderColor="rgb(0,175,25)"
    detectedBorderWidth={6}
  />
  <TouchableOpacity onPress={handleCapture} style={styles.button}>
    <View style={styles.innerButton} />
  </TouchableOpacity>
  <View style={styles.bottom}>
    <Text style={styles.disclaimer}>
      Fixez le document pour le scanner automatiquement.
      En cas d’échec, vous pouvez prendre la photo manuellement.
    </Text>
  </View>
</SafeAreaView>
```

And `handleRectangle` is just a wrapper for `useState` to update `rect`.

All of this works on iPhone 6 (both dev and release versions) and on Android.

Dependencies:

```
    "@babel/runtime": "^7.7.7",
    "@react-native-community/async-storage": "^1.7.1",
    "@react-native-community/datetimepicker": "^2.1.0",
    "bugsnag-react-native": "^2.23.4",
    "date-fns": "^2.8.1",
    "final-form": "^4.18.6",
    "react": "16.9.0",
    "react-final-form": "^6.3.3",
    "react-native": "^0.61.5",
    "react-native-gesture-handler": "^1.5.3",
    "react-native-image-picker": "^2.2.0",
    "react-native-image-resizer": "^1.1.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-reanimated": "^1.7.0",
    "react-native-rectangle-scanner": "^1.0.8",
    "react-native-screens": "^2.0.0-alpha.22",
    "react-native-signature-capture": "^0.4.10",
    "react-native-svg": "^11.0.1",
    "react-native-svg-charts": "^5.3.0",
    "react-native-view-pdf": "^0.10.1",
    "react-native-webview": "^8.0.5",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.7.0",
    "rn-fetch-blob": "^0.12.0",
    "standard-http-error": "^2.0.1"
```

**Comment by humphreyja** [comment]
@antoinerousseau thanks for the details. Is this an **iPhone 8 Plus**? Also what version of iOS are you running?

**Comment by antoinerousseau** [comment]
Sorry yes iPhone 8+, iOS 13.3.1

**Comment by humphreyja** [comment]
Thanks @antoinerousseau I'll see if I can find a way to reproduce this and report what I find.

**Comment by antoinerousseau** [comment]
@humphreyja thank you! :)

**Comment by kev-chen** [comment]
@antoinerousseau I was facing the same issue on an iPhone SE and iPhone XS, both on iOS 13.3.1. I dug around a bit and it looks like starting the camera session blocks the main UI and freezes the preview. I opened PR #25 to fix this issue, hopefully that solves the problem for you.

**Comment by antoinerousseau** [comment]
@kev-chen I can confirm that your PR fixes the issue, thank you!

**Comment by jayan2019** [comment]
Please publish this fix

**Comment by humphreyja** [comment]
@jayan2019 Thanks for reminding me! I'll have this out in a few minutes!
