### ISSUE TITLE
Slow on Android

### ISSUE THREAD

**Issue by antoinerousseau** [HarvestProfit/react-native-rectangle-scanner#27]
After switching from `react-native-document-scanner` to this lib, the Android version is slow at capturing (about 5 seconds). Noticed this on various models. Let me know if I can do anything to dig into it.

**Comment by RaphaelPI** [comment]
@antoinerousseau Same here, it's a bit slow after the picture is taken.

**Comment by humphreyja** [comment]
What image quality setting are you capturing on?

One of the reasons why I added the separate `onPictureTaken` and `onPictureProcessed` callbacks was writing the image(s) to the file system takes the most amount of time.  

Also, here's some additional thoughts on optimizing.

#### Android auto focus
On capture, android has to auto focus before starting the capture [here](https://github.com/HarvestProfit/react-native-rectangle-scanner/blob/master/android/src/main/java/com/rectanglescanner/views/CameraDeviceController.java#L448). Ideally, the system should be auto focusing continuously so what's the point of triggering a refocus again?

#### image quality
If you specify a higher jpeg image quality (> 0.8 lets say), the actual image size is larger and can take longer to save the photo, so setting that number to lower may be desired. I noticed with some of the other packages that the `ImageProcessor.java` file would scale the cropped image down. For example `height = src.size.height / 500`. I removed all of that, so this easily could be related to final image capture quality/size. Reducing the image quality might not be enough though, maybe we should add a scale option to the component to scale the image size too.

#### Time Testing
The easiest way to check these would just be logging the time for some of those capture functions to run. So log the time difference for the `CameraDeviceController.captureImageLater` func and the `CameraDeviceController.onPictureTaken` func to see how long the auto focus step is taking.

Then log the final `RNRectangleScannerView.onProcessedCapturedImage` to see how long storing the images is taking. 

My original thoughts with adding the `onPictureTaken` and `onPictureProcessed` was to allow people to capture higher quality images while showing their customers a loading screen (or transitioning to a different view AND then load the image once the processed callback was triggered. But I noticed that often times you don't need to capture the highest quality image. For my company's use case, our images were huge and took longer than desired to upload to the server after capture. So reducing the quality worked for us.

**Comment by antoinerousseau** [comment]
@humphreyja thank you for the complete feedback, I'll play with these settings next week and I'll let you know!

**Comment by humphreyja** [comment]
@antoinerousseau issue #28 seems to be related to getting stuck because of the autofocus on capture as well. I'm leaning towards removing that block of code.

**Comment by antoinerousseau** [comment]
Maybe you could make an `autofocus` option (prop)

**Comment by humphreyja** [comment]
That might not be the ideal solution as this package should always be autofocusing. The problem is android, actually specific android hardware. Not every device supports continuous autofocus or even autofocus. 

I think I'll end up removing it. But maybe I can trigger it to autofocus every few seconds (to mimic a continuous autofocus). This is something that would get enabled on setting up the camera so it wouldn't run for every device. That way the capture button is more instant.

**Comment by MRdayani** [comment]
How to work in Android ?????
