### ISSUE TITLE
NdkCompile is no longer support !!!

### ISSUE THREAD

**Issue by thomaslc66** [HarvestProfit/react-native-rectangle-scanner#35]
Hello,

Realy nice library and amazong work. Is it possible for you to check and update your library ?

![image](https://user-images.githubusercontent.com/9827392/77255087-41396a80-6c65-11ea-9987-648f9bd1fe4c.png)

**Comment by humphreyja** [comment]
@thomaslc66 Yeah I can look into this quick. I think it's as easy as just removing a line from the gradle.properties file. But I need to find out if it has other implications.

**Comment by humphreyja** [comment]
@thomaslc66 Could you try PR #36 and see if that fixes your issue? I haven't gotten that error before and removing the flag doesn't seem to throw any errors for me.
