### ISSUE TITLE
After taking the picture the app does nothing (Android) 

### ISSUE THREAD

**Issue by cagv24** [HarvestProfit/react-native-rectangle-scanner#39]
Hi, thank you in advance for contributing to this field.

I'm trying to use the complete example, but for some reason, after I take the photo nothing happened.
Do you know what can be causing this problem?

**Comment by humphreyja** [comment]
@cagv24 Here's a few things you can try. The `onErrorProcessingImage`event will return an error message if there was an error during capture. Check this to see if there is something failing. There's also the `onPictureTaken` event should return the path to where the captured images will be saved (this is before the write operation). If this succeeds, then listen for the `onPictureProcessed` event. This means the image was captured and stored successfully. If none of these run, then there is a larger issue here.

**Comment by cagv24** [comment]
Yes, you're rigth.

It prints this on the console:

 LOG  On Picture Taken...
 LOG  {"croppedImage": "file:///data/user/0/com.scanner/cache/RNRectangleScanner/C0d43e1e6-7e2e-474a-aac9-bb3a6d6d2c4b.png", "initialImage": 
 LOG  On Picture Processed...
 LOG  {"croppedImage": "file:///data/user/0/com.scanner/cache/RNRectangleScanner/C0d43e1e6-7e2e-474a-aac9-bb3a6d6d2c4b.png", "initialImage": "file:///data/user/0/com.scanner/cache/RNRectangleScanner/O04fc073d-8736-4c78-91e8-62dc2a2fe8e1.png"}

So everything seems to be good. I was expecting the next view as the Gif shows 😅.
Thank you for your support.

One last question, do you have any plan on adding automatically photo and/or batch features?

**Comment by humphreyja** [comment]
No problem! Yeah the gif may be a bit confusing. This package was built with minimalism in mind so you can build it any way you want to. 

As for your features, if I understand them correctly, this should be already possible. 
1. Auto capture is actually handled entirely in javascript! So on the `RectangleOverlay` component you set the `allowDetection` flag, which will determine if it has found the correct rectangle (if the last few detections were similar). Then you set the `onDetectedCapture` prop on that component which gets triggered when that component has detected the document.
2. Batch capturing is possible as well. If you simply captured again, it would call the `onPictureProcessed/onPictureTaken` events with paths to the new image. The previous image is not deleted. (They are stored in the cache directory, so they eventually will be deleted on app update, or other times. You should move those images, or do something with them after you finish up with this component)

Hopefully that answers your questions!

**Comment by cagv24** [comment]
Hi, yeah, that is exactly what I need.
After doing some tests to the scanner I found that after taking the picture the images are displayed with zoom in then some information gets missed.

**Comment by humphreyja** [comment]
Could you send a screenshot/examples of the images?

**Comment by cagv24** [comment]
Yes, for sure.

My phone is a Samsung Galaxy S8.

This is the preview:
![preview](https://user-images.githubusercontent.com/28711462/77447062-401b5100-6dbd-11ea-955f-13d91b935e82.jpeg)

And this is the processed image:
![processed](https://user-images.githubusercontent.com/28711462/77447128-4dd0d680-6dbd-11ea-9706-3f6ad61e6c7d.jpeg)

**Comment by cagv24** [comment]
I'm checking the fourPointTransform method and it seems like if I modify the maxWidth and maxHeight with hardcoded I could fit the cropped image as expected. However I think this is not a good way to solve this problem

**Comment by humphreyja** [comment]
@cagv24 This bug has shown up before and it should be fixed. The preview/picture size issue is most likely what is going on here but I'm not sure why it's not working right. If you debug the package, could you send a list of the picture sizes and preview sizes as well as the devices screen size? [This function ](https://github.com/HarvestProfit/react-native-rectangle-scanner/blob/master/android/src/main/java/com/rectanglescanner/views/CameraDeviceController.java#L243-L275) should be selecting the right sizes. 

Also I wrote [This function[(https://github.com/HarvestProfit/react-native-rectangle-scanner/blob/master/android/src/main/java/com/rectanglescanner/helpers/Quadrilateral.java#L29-L51) which takes the preview image size/ratio and adjusts the rectangle for the picture image ratio. So even if the picture/preview sizes are different, it should correct it.

**Comment by cagv24** [comment]
After doing some debug to the java part I check the used sizes on setupCamera are the followings:

Preview Size: 1920x1080
Picture Size: 4032x3024

Does this tell you anything?

**Comment by humphreyja** [comment]
Hmm so I had accounted for these differences [here](https://github.com/HarvestProfit/react-native-rectangle-scanner/blob/master/android/src/main/java/com/rectanglescanner/helpers/ImageProcessor.java#L129-L130). Basically it detects a rectangle on the preview screen size. The preview screen size is always 100% shown on the screen (this is why the `onDeviceSetup` returns the height and width % so the view can be adjusted and the preview is not skewed). BUT often the picture size is different, so on capture, it should be taking the captured image and cropping it to the ratio of the preview size before applying the rectangle. 

My point with that jargon is that the difference of ratios should be supported. So I'm thinking that debugging those lines as well as [Quadrilateral.cropImageToRectangleSize](https://github.com/HarvestProfit/react-native-rectangle-scanner/blob/master/android/src/main/java/com/rectanglescanner/helpers/Quadrilateral.java#L29) and (Quadrilateral.getPointsForSize)[https://github.com/HarvestProfit/react-native-rectangle-scanner/blob/master/android/src/main/java/com/rectanglescanner/helpers/Quadrilateral.java#L56] might yield and answer here.

Also good point on the optimal resolution function. I think it needs to take the ratio but also the highest resolution. We want the captured image to be high quality (also why I support different ratios, so this shouldn't matter). Maybe adding a margin on it so it takes the best fitting ratio first, then if the resolution is above a certain amount (like if it is 2x larger), then take the higher resolution.
