### ISSUE TITLE
Make rationale in askForAndroidCameraForPermission() optional

### ISSUE THREAD

**Issue by toomaas** [HarvestProfit/react-native-rectangle-scanner#40]
In `Scanner.js`, when asking for android Camera Permissions , the `rationale` object contains a hardcoded title and message which may not be appropriate to everyone's use cases:
```
const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.CAMERA,
        {
          title: '"Driver" Would Like to Access the Camera?',
          message: 'Allows you to scan scale tickets.',
          buttonNegative: "Don't Allow",
          buttonPositive: 'OK',
        },
      );
```
To prevent this dialog from appearing in my app i asked for permissions before rendering the Scanner component.
Can this dialog box be optionally disabled or editable?

**Comment by humphreyja** [comment]
@toomaas Good eye! I'm surprised it made it this long before it was noticed! I definitely intended this to be customizable before release but obviously I missed this (that is from my company's app that this was extracted from 😳). 

I'll add a simple prop for the title and message as well as a way to disable it entirely. That should give everyone the flexibility they need.
