### ISSUE TITLE
on picture taken base64

### ISSUE THREAD

**Issue by kimsean** [HarvestProfit/react-native-rectangle-scanner#47]
is there a base64 return value of the image taken /.

**Comment by humphreyja** [comment]
@kimsean I actually have decided not to implement this feature and here is why. 

First is that it is a pretty slow operation (at least when I tried it, it actually crashed my app - iOS). Second, this is a simple feature that can be implemented outside of the package using something like `react-native-fetch-blob` as seen here https://stackoverflow.com/questions/34908009/react-native-convert-image-url-to-base64-string.  No sense in reinventing the wheel!

**Comment by kimsean** [comment]
Alright Thanks. I just used react-native-fs converted to convert the file into base64. Thanks for the reply
