### ISSUE TITLE
Generating the release APK failed

### ISSUE THREAD

**Issue by clearproof** [HarvestProfit/react-native-rectangle-scanner#51]
I get the following exception after running ./gradlew bundleRelease:

```
> Task :openCVLibrary310:compileReleaseAidl FAILED
aidl.exe E 04-26 02:08:01  6812 17520 io_delegate.cpp:50] Failed to GetFullPathName(C:\myapp\node_modules\react-native-rectangle-scanner\android\openCVLibrary310\build\generated\aidl_source_output_dir\release\compileReleaseAidl\out\org\opencv\engine\OpenCVEngineInterface.java)
```
Strangely my debug build works well and I can run the app on android without any issues. Only when I try to generate a release APK, it fails. 
Any ideas?

Thanks

**Comment by clearproof** [comment]
Somehow the OpenCVEngineInterface.java file is missing only for the release folder located at C:\myapp\node_modules\react-native-rectangle-scanner\android\openCVLibrary310\build\generated\aidl_source_output_dir\release\compileReleaseAidl\out\org\opencv\engine.

**Comment by humphreyja** [comment]
Hmm I haven't ran across this one yet. Here's some things you can try. 
1. When in doubt, `Invalidate Cache & Restart` often helps.
2. Check you grade settings, any errors? 
3. Check the issues of [This Project](https://github.com/Michaelvilleneuve/react-native-document-scanner) or [This Project](https://github.com.cnpmjs.org/Woonivers/react-native-document-scanner) to see if anyone else had this issue. These were the original packages that the android portion of this package was built from. 

What Versions (Gradle, React, etc) are you using?

**Comment by clearproof** [comment]
Thanks for your help, I've tried a lot of different things but none of them worked, so I just initialized a fresh project and everything worked fine. 

Btw, great scanner !!
