### ISSUE TITLE
requireNativeComponent(...) was not found

### ISSUE THREAD

**Issue by band94** [HarvestProfit/react-native-rectangle-scanner#57]
I've started a project in expo with bare workflow and when i complete the tutorial.
Then i hen i get the following error in ios and android both:
Though i run the `react-native link react-native-rectangle-scanner` command to link the plugin.

```
Invariant Violation: requireNativeComponent: "RNRectangleScanner" was not found in the UIManager.

This error is located at:
    in RNRectangleScanner (at Scanner.js:151)
    in Scanner (at App.js:18)
    in DocumentScanner (at withExpoRoot.js:26)
    in ExpoRoot (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in DevAppContainer (at AppContainer.js:115)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

getNativeComponentAttributes
    getNativeComponentAttributes.js:30:4
exports.get
    ReactNativeViewConfigRegistry.js:102:25
renderRoot
    [native code]:0
runRootCallback
    [native code]:0
renderApplication
    renderApplication.js:52:52
runnables.appKey.run
    AppRegistry.js:116:10
runApplication
    AppRegistry.js:197:26
callFunctionReturnFlushedQueue
    [native code]:0
```

**Comment by humphreyja** [comment]
Do you have any other "rectangle/document" scanner packages installed? Sometimes this causes issues.

**Comment by mikikanez** [comment]
Seems you are using Expo. I think it's not available on Expo... It would be great.

**Comment by humphreyja** [comment]
closing. Expo hasn't graced us with adding us to their API yet. See #45 

Also, toss a vote here and maybe we can get Expo's attention on something like this: https://expo.canny.io/feature-requests/p/react-native-document-scanner

**Comment by dFelinger** [comment]
If you don't using expo and run into this issue:
In node_modules move RNRectangleScanner.podspec file from ios folder to root of the project
Fix path for package.json and s.source_files   = 'ios/**/*.{h,m}'
And run pod install
