### ISSUE TITLE
iOS - Camera shows as black screen

### ISSUE THREAD

**Issue by Pranav-794** [HarvestProfit/react-native-rectangle-scanner#66]
Testing with the example code and on iOS the camera loads up and just goes to a black screen. This is a real device. On android, everything seems to be working fine.

I copied over the full example code you have and tried on both iOS and Android. Android works flawlessly.

Am I missing something? 

Thanks.

**Comment by humphreyja** [comment]
Can you check if the `onDeviceSetup` returns an object that has the `hasCamera` equal to `true`? That's what I immediately think it could be. Also, I've heard there may be issues with conflicting projects. If you have any other `document-scanner` package, it might be causing problems.

**Comment by Pranav-794** [comment]
Trying out your example, and I don't think it even finished setting up. Just stuck on Loading Camera...I do not have other packages related to document scanning.

**Comment by humphreyja** [comment]
hmm has it asked for permission to access the camera at least?

**Comment by Pranav-794** [comment]
On IOS it has not. Android it does ask for permission.

**Comment by onursagir** [comment]
Did u try adding `NSCameraUsageDescription` to Info.plist?

**Comment by Pranav-794** [comment]
It works after I included the NSCameraUsageDescription tag in the Info.plist. Thanks.

**Comment by humphreyja** [comment]
@onursagir Thanks for the tip! I added this to the documentation
