### ISSUE TITLE
Expo Request

### ISSUE THREAD

**Issue by GrahamEvans31** [HarvestProfit/react-native-rectangle-scanner#94]
Hi,

I'd love to see this available as an expo module, our team is currently looking to make use of this type of technology for some document submission tools.  We like expo as it makes it much easier to maintain and develop our project without so much in depth knowledge of each android/ios projects.

**Comment by stdavis** [comment]
This has already been answered in #45.

**Comment by humphreyja** [comment]
@GrahamEvans31 Hey yeah I saw your comments on the Expo feature request and yeah unfortunately #45 does pretty much sum this all up. Personally I think it will never be allowed to work with Expo until Android starts providing some sort of image analysis API. It'd be hard for the folks at Expo to justify adding the entire OpenCV library to their framework. 

Though I'd be curious if you make any headway with that EAS stuff. If you manage to get it working, please share with the community!

**Comment by GrahamEvans31** [comment]
I actually started to trend in a different direction, what I'm looking for now is a server-side image solution.  Both Android/iOS take amazing pictures, although it would be better to have it perform the image pre-processing right when capturing to let the user know they got a good image but it would also be easy to have a offline job for processing and a reject/verification workflow.  Just trying to avoid messing with the inner-workings of 2 different operating systems for the same type of instrument.  Haven't found what I'm looking for yet... thanks for the reply though and I will share if I get anything working.

**Comment by humphreyja** [comment]
UPDATE: Thanks to expo 50 and their development builds, this now works in Expo! Currently deploying our app in expo with this package installed. Made a few updates in #115 to ensure that it builds correctly including an update to openCV.

I'm doing some internal testing on our app currently and after I'll release an update to NPM.
